import type { Floor, Table, Booking } from "@/types"

export const demoFloors: Floor[] = [
  {
    id: "floor-1",
    floorNumber: 1,
    name: "Ground Floor",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "floor-2",
    floorNumber: 2,
    name: "First Floor",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "floor-3",
    floorNumber: 3,
    name: "Rooftop",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const demoTables: Table[] = [
  // Ground Floor
  {
    id: "t1",
    tableNumber: "T1",
    size: "SMALL",
    status: "AVAILABLE",
    floorId: "floor-1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t2",
    tableNumber: "T2",
    size: "SMALL",
    status: "BOOKED",
    floorId: "floor-1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t3",
    tableNumber: "T3",
    size: "MEDIUM",
    status: "OCCUPIED",
    floorId: "floor-1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t4",
    tableNumber: "T4",
    size: "MEDIUM",
    status: "AVAILABLE",
    floorId: "floor-1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t5",
    tableNumber: "T5",
    size: "LARGE",
    status: "BOOKED",
    floorId: "floor-1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t6",
    tableNumber: "T6",
    size: "MEDIUM",
    status: "AVAILABLE",
    floorId: "floor-1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t7",
    tableNumber: "T7",
    size: "SMALL",
    status: "AVAILABLE",
    floorId: "floor-1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t8",
    tableNumber: "T8",
    size: "LARGE",
    status: "OCCUPIED",
    floorId: "floor-1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // First Floor
  {
    id: "t9",
    tableNumber: "T9",
    size: "SMALL",
    status: "AVAILABLE",
    floorId: "floor-2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t10",
    tableNumber: "T10",
    size: "MEDIUM",
    status: "BOOKED",
    floorId: "floor-2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t11",
    tableNumber: "T11",
    size: "MEDIUM",
    status: "AVAILABLE",
    floorId: "floor-2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t12",
    tableNumber: "T12",
    size: "LARGE",
    status: "OCCUPIED",
    floorId: "floor-2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t13",
    tableNumber: "T13",
    size: "SMALL",
    status: "AVAILABLE",
    floorId: "floor-2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t14",
    tableNumber: "T14",
    size: "MEDIUM",
    status: "AVAILABLE",
    floorId: "floor-2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t15",
    tableNumber: "T15",
    size: "LARGE",
    status: "BOOKED",
    floorId: "floor-2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t16",
    tableNumber: "T16",
    size: "SMALL",
    status: "AVAILABLE",
    floorId: "floor-2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Rooftop
  {
    id: "t17",
    tableNumber: "T17",
    size: "MEDIUM",
    status: "AVAILABLE",
    floorId: "floor-3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t18",
    tableNumber: "T18",
    size: "LARGE",
    status: "BOOKED",
    floorId: "floor-3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t19",
    tableNumber: "T19",
    size: "MEDIUM",
    status: "OCCUPIED",
    floorId: "floor-3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t20",
    tableNumber: "T20",
    size: "LARGE",
    status: "AVAILABLE",
    floorId: "floor-3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t21",
    tableNumber: "T21",
    size: "SMALL",
    status: "AVAILABLE",
    floorId: "floor-3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "t22",
    tableNumber: "T22",
    size: "MEDIUM",
    status: "BOOKED",
    floorId: "floor-3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const demoBookings: Booking[] = [
  {
    id: "b1",
    customerName: "John Smith",
    mobile: "+1-555-0101",
    email: "john.smith@email.com",
    peopleCount: 2,
    bookingTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    status: "BOOKED",
    tableId: "t2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "b2",
    customerName: "Sarah Johnson",
    mobile: "+1-555-0102",
    email: "sarah.j@email.com",
    peopleCount: 6,
    bookingTime: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    status: "BOOKED",
    tableId: "t5",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "b3",
    customerName: "Michael Brown",
    mobile: "+1-555-0103",
    peopleCount: 4,
    bookingTime: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    status: "BOOKED",
    tableId: "t10",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "b4",
    customerName: "Emily Davis",
    mobile: "+1-555-0104",
    email: "emily.d@email.com",
    peopleCount: 6,
    bookingTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    status: "BOOKED",
    tableId: "t15",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "b5",
    customerName: "David Wilson",
    mobile: "+1-555-0105",
    peopleCount: 6,
    bookingTime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    status: "BOOKED",
    tableId: "t18",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "b6",
    customerName: "Jessica Martinez",
    mobile: "+1-555-0106",
    email: "jessica.m@email.com",
    peopleCount: 4,
    bookingTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    status: "BOOKED",
    tableId: "t22",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
